---
- name: "set fact: first Swarm manager host"
  set_fact:
    first_swarm_manager_host: managers[0]

- name: Joining worker to the swarm
  # https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html
  community.general.docker_swarm:
    state: join
    timeout: 60
    # Using PRIVATE IP ADDRESS as they are in the same VPC
    advertise_addr: first_swarm_manager_host:2377
    # hostvars contains all variables related to a host
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#accessing-information-about-other-hosts-with-magic-variables
    join_token: >-
      { { join_token_worker } }
    # Using PRIVATE IP ADDRESS as they are in the same VPC
    remote_addrs: ["206.81.21.94", "206.81.30.23"]
