version: 2.1

jobs:
  setup_infrastructure:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Generate the SSH files
          command: |
            echo $pvt_key >> terraform
            echo $pub_key >> terraform.pub
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run:
          name: Install Ansible
          command: |
            sudo apt install software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible
      - run:
          name: Terraform Init
          command: |
            terraform init
      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve -var "do_token=$do_token" -var "pvt_key=$path_to_pvt_key" -var "pub_key=$path_to_pub_key"
workflows:
  version: 2.1
  build:
    jobs:
      - setup_infrastructure
