version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2022.06
  working_directory: ~/project
  environment:
    TF_IN_AUTOMATION: true

tf-install: &tf-install
  run:
    name: Install Terraform
    command: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
      terraform --version

ansible-install: &ansible-install
  run:
    name: Install Ansible
    command: |
      sudo apt install software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt install ansible

jobs:
  terraform-init:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - *tf-install
      - run:
          name: terraform init
          command: terraform -chdir=terraform/envs/production init -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *tf-install
      - run:
          name: Generate the SSH files
          command: |
            echo $pvt_key >> terraform/envs/production/terraform
            echo $pub_key >> terraform/envs/production/terraform.pub
      - run:
          name: terraform plan
          command: terraform -chdir=terraform/envs/production plan -var "do_token=$do_token" -var "pvt_key=$path_to_pvt_key" -var "pub_key=$path_to_pub_key" -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-apply-approval:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *tf-install
      - *ansible-install
      - run:
          name: terraform apply
          command: terraform -chdir=terraform/envs/production apply -auto-approve -var "do_token=$do_token" -var "pvt_key=$path_to_pvt_key" -var "pub_key=$path_to_pub_key" -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2.1
  setup_infrastructure:
    jobs:
      - terraform-init:
          filters:
            branches:
              only: master
      - terraform-plan:
          requires:
            - terraform-init
      - hold-for-approval:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply-approval:
          requires:
            - hold-for-approval
